name: Send to Feishu
on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Feishu
        uses: XRSec/feishu-bot-webhook-action@v1
        with:
          FEISHU_BOT_WEBHOOK: https://open.feishu.cn/open-apis/bot/v2/hook/498e0e3e-e39d-4c34-9a72-10d85deebe3d
